version: '1.0.0'
services:
  api: 
    build:
      dockerfile: Dockerfile
      context: .
      # target: development
    # command: npm run start:dev
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - home-library-service-network
    depends_on:
      - postgres
    restart: always
  postgres:
    build:
      dockerfile: db.Dockerfile
      context: .
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - app-postgres-data:/var/lib/postgresql/data
    networks:
      - home-library-service-network
    restart: always

volumes:
  app-postgres-data:
networks:
  home-library-service-network:
    driver: bridge
